{
	"OnFailure": "/SalesOrdersOffline/Rules/Common/UpdateRequiredFailed.js",
	"OnSuccess": "/SalesOrdersOffline/Actions/SalesOrder/CreateUpdateDelete/SOHeaderCreate.action",
	"RequiredFields": [
		"ObjectCellListPickerCustomerId",
		"SimplePropertyCurrencyCode"
	],
	"_Type": "Action.Type.CheckRequiredFields"
}